list1 = [
  {'appear' : 'появляться'},
  {'issues' : 'вопросы'},
  {'provide' : 'предоставлять'},
  {'define' : 'определять'},
  {'respectively' : 'соответственно'},
  {'corresponding' : ['соответствующий', 'подобный']},
  {'footer' : 'нижний колонтитул'},
  {'aligned' : 'выровнять'},
  {'brackets' : 'скобки'},
  {'instead' : 'вместо'},
  {'themselves' : 'сами себя'},
  {'denotes' : 'обозначает'},
  {'allows' : 'позволяет'},
  {'embed' : 'вставлять'},
  {'advertising' : 'реклама'},
  {'advertise' : 'рекламировать'},
  {'unifying' : 'объединяющий'},
  {'aim' : 'цель'},
  {'dependable' : 'надежный'},
  {'commonly' : 'обычно'},
  {'rather' : 'скорее'},
  {'advantage' : 'преимущество'},
  {'abilities' : 'способности'},
  {'plain' : 'простой'},
  {'offer' : 'предложение'},
  {'property' : 'имущество'},
  {'certain' : 'определенный'},
  {'describe' : 'описывает'},
  {'consumers' : 'потребители'},
  {'gracefully' : 'изящно'},
  {'able' : 'способный'},
  {'seamless' : ['цельный', 'бесшовный']},
  {'require' : 'требовать'},
  {'involves' : 'включает в себя'},
  {'achieve' : 'достигать'},
  {'deploying' : 'развертывание'},
  {'behavior' : 'поведение'},
  {'behavior-driven' : 'поведенческий'},
  {'implement' : ['осуществлять', 'реализовывать']},
  {'both' : 'оба'},
  {'collaborative' : 'совместный'},
  {'branching' : 'ветвление'},
  {'occurs' : 'имеет место'},
  {'commit' : 'совершать, вводить в дело'},
  {'issues' : 'вопросы'},
  {'bulk' : ['основная масса', 'масса']},
  {'cognitive' : 'познавательный'},
  {'parsing' : 'разбор'},
  {'workflows' : 'рабочие процессы'},
  {'either' : ['либо', 'или']},
  {'compatibility' : 'совместимость'},
  {'particular' : 'конкретный'},
  {'redundancy' : 'избыточность'},
  {'thus' : ['таким образом', 'поэтому']},
  {'purchase' : ['покупка', 'приобретение']},
  {'viable' : 'жизнеспособный'},
  {'nested' : 'вложенный'},
  {'narrow' : 'узкий'},
  {'consider' : 'рассмотреть'},
  {'decision' : 'решение'},
  {'compared' : 'сравнивание'},
  {'evolving' : 'развивающийся'},
  {'versatile' : 'универсальный'},
  {'notorious' : 'пресловутый'},
  {'cumbersome' : 'громоздкий'},
  {'concerning' : 'касательно'},
  {'however' : 'однако'},
  {'widespread' : 'широко распространенный'},
  {'claiming' : 'заявляя'},
  {'fairly' : 'весьма'},
  {'straightforward' : ['простой', 'прямой', 'откровенный']},
  {'least' : 'наименьшее'},
  {'pleasant' : 'приятный'},
]

for i in list1:
  for k, v in i.items():
    print(f"{k}", end = '')
    while True:
      try:
        word = str(input(' : '))
        if word in v:
          break         
        else:
          print('Wrong!')
          print(f"{k}", end = '')
      except:
        print('')